version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run dev