name: Rpi-Server

on:
    push:
        paths:
            - 'rpi-server/**'
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: rpi-server

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 20.x
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
